Repository Staffbase/gha-workflows, pull requests merged in 2022-09, with the labels that each got.

#59 Update Staffbase jobs uri
  README.md
Labels: documentation, patch

#61 :sparkles: Added backstage-techdocs action
  .github/workflows/template_techdocs.yml
  README.md
Labels: minor

#63 :memo: improve techdocs documentation
  .github/workflows/template_techdocs.yml
  README.md
Labels: documentation, patch

#66 🎨 Improve autodev
  .github/workflows/template_autodev.yml
  README.md
Labels: enhancement, patch

#68 :sparkles: Update TechDocs action to make use of additional-plugins
  .github/workflows/template_techdocs.yml
  README.md
Labels: enhancement, minor
