Repository Staffbase/gha-workflows, pull requests merged in 2022-06, with the labels that each got.

#31 :art: add check for dependabot in autodev
  .github/workflows/template_autodev.yml
Labels: enhancement, patch

#32 :rewind: revert direct gitops usage
  .github/workflows/template_gitops.yml
Labels: bug, patch

#34 :construction_worker: add update readme workflow
  .github/workflows/versions.yml
Labels: enhancement, patch

#36 CLP-0000: Add "dockerenabled" input to GitOps template
  .github/workflows/template_gitops.yml
  README.md
Labels: enhancement, patch

#40 :bug: fix wrong input field
  .github/workflows/template_gitops.yml
Labels: bug, patch

#41 Add staffbase doc
  README.md
  docs/assets/images/staffbase.png
Labels: documentation, patch

#44 :art: add jira default name
  .github/workflows/template_jira_tagging.yml
  README.md
Labels: enhancement, patch

#39 🎨 Add projectBaseDir to sonarcloud template
  .github/workflows/template_sonarcloud.yml
  README.md
Labels: enhancement, patch
