Repository Staffbase/gha-workflows, pull requests merged in 2023-09, with the labels that each got.

#160 :art: Improve next release version
  .github/workflows/template_release_version.yml
Labels: enhancement, patch

#165 :bug: Fix release check
  .github/workflows/template_release_version.yml
Labels: bug, patch

#168 :art: Improve release check
  .github/workflows/template_release_version.yml
Labels: bug, patch

#170 :sparkles: GitOps: add working-directory parameter
  .github/workflows/template_gitops.yml
  README.md
Labels: enhancement, minor

#175 Update github-action-jira-release-tagging
  .github/workflows/template_jira_tagging.yml
Labels: dependencies, minor

#177 Add timdittler to CLA allowlist
  .github/workflows/cla.yml
Labels: documentation, patch
