Repository Staffbase/gha-workflows, pull requests merged in 2023-07, with the labels that each got.

#134 Bump autodev action to 1.8.0
  .github/workflows/template_autodev.yml
Labels: enhancement, minor

#136 :arrow_up: Bump readme version
  README.md
Labels: documentation, patch

#131 :sparkles: Trigger a manual test on crowd-testing provider TestIO
  .github/workflows/template_testio_trigger_test.yml
  README.md
Labels: enhancement, minor

#138 ⬆️ set testio action version to v1.0.0 instead of main
  .github/workflows/template_testio_trigger_test.yml
Labels: dependencies, minor

#137 📝 increase version numbers in README.md
  README.md
Labels: documentation, patch

#143 :alembic: Using single autodev action
  .github/workflows/template_autodev.yml
  README.md
Labels: enhancement, minor
