Repository Staffbase/gha-workflows, pull requests merged in 2023-11, with the labels that each got.

#187 :art: Create dependabot automerge action
  .github/workflows/template_automerge_dependabot.yml
  README.md
Labels: enhancement, minor

#122 :fire: Remove explicit tokens
  .github/workflows/template_gitops.yml
  README.md
Labels: enhancement, major

#191 :art: Add approval for pull request
  .github/workflows/template_automerge_dependabot.yml
Labels: enhancement, minor

#193 :memo: Update version resolve documentation
  README.md
Labels: documentation, patch

#194 :art: Using github app for auto merge
  .github/workflows/template_automerge_dependabot.yml
  README.md
Labels: enhancement, minor

#199 :art: Force automerge as admin
  .github/workflows/template_automerge_dependabot.yml
  README.md
Labels: enhancement, minor

#200 ⬆️ Bump TestIO version
  .github/workflows/template_testio_trigger_test.yml
Labels: dependencies, patch

#204 Disable auto-merge for dependency bumps with major version 0
  .github/workflows/template_automerge_dependabot.yml
Labels: enhancement, patch

#206 CIV-424 Rename Storage Name
  .github/workflows/template_techdocs.yml
Labels: enhancement, patch
