Repository Staffbase/gha-workflows, pull requests merged in 2023-03, with the labels that each got.

#103 Use Azure as default publisher for TechDocs
  .github/workflows/template_techdocs.yml
  README.md
Labels: enhancement

#105 Fix wrong propery name
  .github/workflows/template_techdocs.yml
  README.md
Labels: bug

#107 Update yamllint Action
  .github/workflows/template_yaml.yml
Labels: dependencies
