Repository Staffbase/gha-workflows, pull requests merged in 2024-06, with the labels that each got.

#258 :wrench: Add retagging options
  .github/workflows/template_gitops.yml
  README.md
Labels: enhancement, patch

#260 :construction_worker: Add custom token for PR creation
  .github/workflows/versions.yml
Labels: bug, patch

#261 Revert "🔥 Remove approving from auto-merge workflow"
  .github/workflows/template_automerge_dependabot.yml
Labels: enhancement, minor

#264 NO-TICKET Update default gitops-email and gitops-user
  .github/workflows/template_gitops.yml
  README.md
Labels: bug, patch
