Repository Staffbase/gha-workflows, pull requests merged in 2024-10, with the labels that each got.

#286 CLP-0000: Add an input type to specify update types for dependabot automerge workflow
  .github/workflows/template_automerge_dependabot.yml
  README.md
Labels: enhancement, minor

#289 Revert "chore(deps): bump Staffbase/gitops-github-action from 6.2 to 6.3"
  .github/workflows/template_gitops.yml
Labels: enhancement, minor

#265 Bump techdocs version
  .github/workflows/template_techdocs.yml
Labels: dependencies, patch

#288 Emit image build event for upwind
  .github/workflows/template_gitops.yml
  README.md
Labels: enhancement, minor

#285 :arrow_up: Bump ubuntu image
  .github/CODEOWNERS
  .github/workflows/cla.yml
  .github/workflows/template_autodev.yml
  .github/workflows/template_automerge_dependabot.yml
  .github/workflows/template_gitops.yml
  .github/workflows/template_jira_tagging.yml
  .github/workflows/template_launchdarkly_code_references.yml
  .github/workflows/template_merge_block.yml
  .github/workflows/template_release_drafter.yml
  .github/workflows/template_release_version.yml
  .github/workflows/template_secret_scan.yml
  .github/workflows/template_stale.yml
  .github/workflows/template_techdocs.yml
  .github/workflows/template_testio_trigger_test.yml
  .github/workflows/template_yaml.yml
  .github/workflows/versions.yml
Labels: dependencies, major
