Repository Staffbase/gha-workflows, pull requests merged in 2025-04, with the labels that each got.

#326 :bug: Fix week number
  .github/workflows/template_release_version.yml
Labels: bug, patch

#314 feat: add flaky tests template
  .github/workflows/cla.yml
  .github/workflows/template_flaky_tests.yml
  README.md
Labels: enhancement, minor, hackathon

#328 :art: Add release drafter config name
  .github/workflows/template_release_drafter.yml
  README.md
Labels: enhancement, minor
